### ISSUE TITLE
guest permissions

### ISSUE THREAD

**Issue by jKwibe** [Practice-Hacker/main-app#7]
Feature: Guest User Permissions

Story:
As a guest user that has not registered or authenticated,
I can browse for music and search for music, but I cannot add tips, follow users, favorite pieces, etc.

**Comment by twarbelow** [comment]
@ckccameron what do you think about splitting this up into the stories that deal with adding tips/following users/ and favoriting pieces? it is difficult to implement this when the other functionality is not there yet.

ie as a logged in user I can add a tip to a piece
as a guest, I do not have the option to add a tip to a piece?

**Comment by twarbelow** [comment]
I think that this will essentially entail checking current_user for the add a tip button, follow a user button, and favoriting a piece button.

**Comment by twarbelow** [comment]
Kwibe is working on search, I will add this guest logic once he is done.

@jKwibe please ping me when you are done with that functionality
